In [1]:
from preprocess.load_data.data_loader import load_hotel_reserve

In [2]:
customer_tb, hotel_tb, reserve_tb = load_hotel_reserve()

In [3]:
# 下の行から本書スタート
# loc関数の2次元配列の2次元目に抽出したい列名の配列を指定することで、列を抽出
reserve_tb.loc[:, ['reserve_id', 'hotel_id', 'customer_id',
                   'reserve_datetime', 'checkin_date',
                   'checkin_time', 'checkout_date']]

<div>
<style scoped>
    .dataframe tbody tr th:only-of-type {
        vertical-align: middle;
    }

    .dataframe tbody tr th {
        vertical-align: top;
    }

    .dataframe thead th {
        text-align: right;
    }
</style>
<table border="1" class="dataframe">
  <thead>
    <tr style="text-align: right;">
      <th></th>
      <th>reserve_id</th>
      <th>hotel_id</th>
      <th>customer_id</th>
      <th>reserve_datetime</th>
      <th>checkin_date</th>
      <th>checkin_time</th>
      <th>checkout_date</th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <th>0</th>
      <td>r1</td>
      <td>h_75</td>
      <td>c_1</td>
      <td>2016-03-06 13:09:42</td>
      <td>2016-03-26</td>
      <td>10:00:00</td>
      <td>2016-03-29</td>
    </tr>
    <tr>
      <th>1</th>
      <td>r2</td>
      <td>h_219</td>
      <td>c_1</td>
      <td>2016-07-16 23:39:55</td>
      <td>2016-07-20</td>
      <td>11:30:00</td>
      <td>2016-07-21</td>
    </tr>
    <tr>
      <th>2</th>
      <td>r3</td>
      <td>h_179</td>
      <td>c_1</td>
      <td>2016-09-24 10:03:17</td>
      <td>2016-10-19</td>
      <td>09:00:00</td>
      <td>2016-10-22</td>
    </tr>
    <tr>
      <th>3</th>
      <td>r4</td>
      <td>h_214</td>
      <td>c_1</td>
      <td>2017-03-08 03:20:10</td>
      <td>2017-03-29</td>
      <td>11:00:00</td>
      <td>2017-03-30</td>
    </tr>
    <tr>
      <th>4</th>
      <td>r5</td>
      <td>h_16</td>
      <td>c_1</td>
      <td>2017-09-05 19:50:37</td>
      <td>2017-09-22</td>
      <td>10:30:00</td>
      <td>2017-09-23</td>
    </tr>
    <tr>
      <th>5</th>
      <td>r6</td>
      <td>h_241</td>
      <td>c_1</td>
      <td>2017-11-27 18:47:05</td>
      <td>2017-12-04</td>
      <td>12:00:00</td>
      <td>2017-12-06</td>
    </tr>
    <tr>
      <th>6</th>
      <td>r7</td>
      <td>h_256</td>
      <td>c_1</td>
      <td>2017-12-29 10:38:36</td>
      <td>2018-01-25</td>
      <td>10:30:00</td>
      <td>2018-01-28</td>
    </tr>
    <tr>
      <th>7</th>
      <td>r8</td>
      <td>h_241</td>
      <td>c_1</td>
      <td>2018-05-26 08:42:51</td>
      <td>2018-06-08</td>
      <td>10:00:00</td>
      <td>2018-06-09</td>
    </tr>
    <tr>
      <th>8</th>
      <td>r9</td>
      <td>h_217</td>
      <td>c_2</td>
      <td>2016-03-05 13:31:06</td>
      <td>2016-03-25</td>
      <td>09:30:00</td>
      <td>2016-03-27</td>
    </tr>
    <tr>
      <th>9</th>
      <td>r10</td>
      <td>h_240</td>
      <td>c_2</td>
      <td>2016-06-25 09:12:22</td>
      <td>2016-07-14</td>
      <td>11:00:00</td>
      <td>2016-07-17</td>
    </tr>
    <tr>
      <th>10</th>
      <td>r11</td>
      <td>h_183</td>
      <td>c_2</td>
      <td>2016-11-19 12:49:10</td>
      <td>2016-12-08</td>
      <td>11:00:00</td>
      <td>2016-12-11</td>
    </tr>
    <tr>
      <th>11</th>
      <td>r12</td>
      <td>h_268</td>
      <td>c_2</td>
      <td>2017-05-24 10:06:21</td>
      <td>2017-06-20</td>
      <td>09:00:00</td>
      <td>2017-06-21</td>
    </tr>
    <tr>
      <th>12</th>
      <td>r13</td>
      <td>h_223</td>
      <td>c_2</td>
      <td>2017-10-19 03:03:30</td>
      <td>2017-10-21</td>
      <td>09:30:00</td>
      <td>2017-10-23</td>
    </tr>
    <tr>
      <th>13</th>
      <td>r14</td>
      <td>h_133</td>
      <td>c_2</td>
      <td>2018-02-18 05:12:58</td>
      <td>2018-03-12</td>
      <td>10:00:00</td>
      <td>2018-03-15</td>
    </tr>
    <tr>
      <th>14</th>
      <td>r15</td>
      <td>h_92</td>
      <td>c_2</td>
      <td>2018-04-19 11:25:00</td>
      <td>2018-05-04</td>
      <td>12:30:00</td>
      <td>2018-05-05</td>
    </tr>
    <tr>
      <th>15</th>
      <td>r16</td>
      <td>h_135</td>
      <td>c_2</td>
      <td>2018-07-06 04:18:28</td>
      <td>2018-07-08</td>
      <td>10:00:00</td>
      <td>2018-07-09</td>
    </tr>
    <tr>
      <th>16</th>
      <td>r17</td>
      <td>h_115</td>
      <td>c_3</td>
      <td>2016-05-10 12:20:32</td>
      <td>2016-05-17</td>
      <td>10:00:00</td>
      <td>2016-05-19</td>
    </tr>
    <tr>
      <th>17</th>
      <td>r18</td>
      <td>h_132</td>
      <td>c_3</td>
      <td>2016-10-22 02:18:48</td>
      <td>2016-11-12</td>
      <td>12:00:00</td>
      <td>2016-11-13</td>
    </tr>
    <tr>
      <th>18</th>
      <td>r19</td>
      <td>h_23</td>
      <td>c_3</td>
      <td>2017-01-11 22:54:09</td>
      <td>2017-02-08</td>
      <td>10:00:00</td>
      <td>2017-02-10</td>
    </tr>
    <tr>
      <th>19</th>
      <td>r20</td>
      <td>h_292</td>
      <td>c_3</td>
      <td>2017-02-23 07:10:30</td>
      <td>2017-03-03</td>
      <td>11:00:00</td>
      <td>2017-03-04</td>
    </tr>
    <tr>
      <th>20</th>
      <td>r21</td>
      <td>h_153</td>
      <td>c_3</td>
      <td>2017-04-06 18:12:10</td>
      <td>2017-04-16</td>
      <td>09:00:00</td>
      <td>2017-04-19</td>
    </tr>
    <tr>
      <th>21</th>
      <td>r22</td>
      <td>h_12</td>
      <td>c_3</td>
      <td>2017-07-24 19:15:54</td>
      <td>2017-08-08</td>
      <td>09:00:00</td>
      <td>2017-08-09</td>
    </tr>
    <tr>
      <th>22</th>
      <td>r23</td>
      <td>h_61</td>
      <td>c_3</td>
      <td>2017-12-16 23:31:04</td>
      <td>2018-01-09</td>
      <td>09:00:00</td>
      <td>2018-01-12</td>
    </tr>
    <tr>
      <th>23</th>
      <td>r24</td>
      <td>h_34</td>
      <td>c_3</td>
      <td>2018-04-27 08:51:07</td>
      <td>2018-05-07</td>
      <td>09:30:00</td>
      <td>2018-05-10</td>
    </tr>
    <tr>
      <th>24</th>
      <td>r25</td>
      <td>h_277</td>
      <td>c_4</td>
      <td>2016-03-28 07:17:34</td>
      <td>2016-04-07</td>
      <td>10:30:00</td>
      <td>2016-04-10</td>
    </tr>
    <tr>
      <th>25</th>
      <td>r26</td>
      <td>h_132</td>
      <td>c_4</td>
      <td>2016-05-11 17:48:07</td>
      <td>2016-06-05</td>
      <td>11:30:00</td>
      <td>2016-06-06</td>
    </tr>
    <tr>
      <th>26</th>
      <td>r27</td>
      <td>h_97</td>
      <td>c_4</td>
      <td>2016-07-08 14:10:06</td>
      <td>2016-07-16</td>
      <td>10:30:00</td>
      <td>2016-07-17</td>
    </tr>
    <tr>
      <th>27</th>
      <td>r28</td>
      <td>h_119</td>
      <td>c_4</td>
      <td>2016-10-07 04:38:54</td>
      <td>2016-11-04</td>
      <td>10:00:00</td>
      <td>2016-11-06</td>
    </tr>
    <tr>
      <th>28</th>
      <td>r29</td>
      <td>h_222</td>
      <td>c_4</td>
      <td>2016-11-10 21:59:02</td>
      <td>2016-11-13</td>
      <td>12:30:00</td>
      <td>2016-11-16</td>
    </tr>
    <tr>
      <th>29</th>
      <td>r30</td>
      <td>h_34</td>
      <td>c_4</td>
      <td>2017-03-14 23:02:05</td>
      <td>2017-03-14</td>
      <td>11:30:00</td>
      <td>2017-03-17</td>
    </tr>
    <tr>
      <th>...</th>
      <td>...</td>
      <td>...</td>
      <td>...</td>
      <td>...</td>
      <td>...</td>
      <td>...</td>
      <td>...</td>
    </tr>
    <tr>
      <th>4000</th>
      <td>r4001</td>
      <td>h_253</td>
      <td>c_993</td>
      <td>2017-01-20 18:50:35</td>
      <td>2017-02-10</td>
      <td>11:00:00</td>
      <td>2017-02-12</td>
    </tr>
    <tr>
      <th>4001</th>
      <td>r4002</td>
      <td>h_263</td>
      <td>c_993</td>
      <td>2017-02-20 16:13:02</td>
      <td>2017-02-27</td>
      <td>10:30:00</td>
      <td>2017-02-28</td>
    </tr>
    <tr>
      <th>4002</th>
      <td>r4003</td>
      <td>h_262</td>
      <td>c_993</td>
      <td>2017-08-01 23:47:40</td>
      <td>2017-08-03</td>
      <td>10:00:00</td>
      <td>2017-08-05</td>
    </tr>
    <tr>
      <th>4003</th>
      <td>r4004</td>
      <td>h_201</td>
      <td>c_993</td>
      <td>2017-08-31 01:33:58</td>
      <td>2017-09-13</td>
      <td>09:30:00</td>
      <td>2017-09-15</td>
    </tr>
    <tr>
      <th>4004</th>
      <td>r4005</td>
      <td>h_150</td>
      <td>c_994</td>
      <td>2016-03-25 11:51:26</td>
      <td>2016-04-02</td>
      <td>09:00:00</td>
      <td>2016-04-03</td>
    </tr>
    <tr>
      <th>4005</th>
      <td>r4006</td>
      <td>h_290</td>
      <td>c_995</td>
      <td>2016-05-14 21:35:27</td>
      <td>2016-06-12</td>
      <td>10:00:00</td>
      <td>2016-06-15</td>
    </tr>
    <tr>
      <th>4006</th>
      <td>r4007</td>
      <td>h_76</td>
      <td>c_995</td>
      <td>2016-07-11 06:45:26</td>
      <td>2016-07-31</td>
      <td>10:30:00</td>
      <td>2016-08-03</td>
    </tr>
    <tr>
      <th>4007</th>
      <td>r4008</td>
      <td>h_52</td>
      <td>c_995</td>
      <td>2016-11-02 06:42:54</td>
      <td>2016-11-27</td>
      <td>12:00:00</td>
      <td>2016-11-28</td>
    </tr>
    <tr>
      <th>4008</th>
      <td>r4009</td>
      <td>h_213</td>
      <td>c_995</td>
      <td>2016-12-10 19:23:02</td>
      <td>2016-12-24</td>
      <td>12:00:00</td>
      <td>2016-12-25</td>
    </tr>
    <tr>
      <th>4009</th>
      <td>r4010</td>
      <td>h_84</td>
      <td>c_995</td>
      <td>2017-02-04 02:00:05</td>
      <td>2017-03-01</td>
      <td>10:00:00</td>
      <td>2017-03-04</td>
    </tr>
    <tr>
      <th>4010</th>
      <td>r4011</td>
      <td>h_137</td>
      <td>c_995</td>
      <td>2017-08-13 19:23:48</td>
      <td>2017-09-07</td>
      <td>09:30:00</td>
      <td>2017-09-09</td>
    </tr>
    <tr>
      <th>4011</th>
      <td>r4012</td>
      <td>h_54</td>
      <td>c_995</td>
      <td>2018-03-08 03:54:07</td>
      <td>2018-03-20</td>
      <td>10:30:00</td>
      <td>2018-03-22</td>
    </tr>
    <tr>
      <th>4012</th>
      <td>r4013</td>
      <td>h_13</td>
      <td>c_995</td>
      <td>2018-07-04 18:54:55</td>
      <td>2018-07-04</td>
      <td>11:00:00</td>
      <td>2018-07-05</td>
    </tr>
    <tr>
      <th>4013</th>
      <td>r4014</td>
      <td>h_27</td>
      <td>c_996</td>
      <td>2016-05-29 18:33:42</td>
      <td>2016-06-11</td>
      <td>12:00:00</td>
      <td>2016-06-14</td>
    </tr>
    <tr>
      <th>4014</th>
      <td>r4015</td>
      <td>h_225</td>
      <td>c_996</td>
      <td>2016-12-03 21:40:17</td>
      <td>2016-12-22</td>
      <td>11:30:00</td>
      <td>2016-12-23</td>
    </tr>
    <tr>
      <th>4015</th>
      <td>r4016</td>
      <td>h_239</td>
      <td>c_996</td>
      <td>2016-12-29 02:10:09</td>
      <td>2017-01-14</td>
      <td>10:30:00</td>
      <td>2017-01-16</td>
    </tr>
    <tr>
      <th>4016</th>
      <td>r4017</td>
      <td>h_96</td>
      <td>c_996</td>
      <td>2017-06-19 11:26:29</td>
      <td>2017-07-05</td>
      <td>10:30:00</td>
      <td>2017-07-07</td>
    </tr>
    <tr>
      <th>4017</th>
      <td>r4018</td>
      <td>h_204</td>
      <td>c_996</td>
      <td>2017-08-20 17:56:37</td>
      <td>2017-09-06</td>
      <td>12:30:00</td>
      <td>2017-09-07</td>
    </tr>
    <tr>
      <th>4018</th>
      <td>r4019</td>
      <td>h_224</td>
      <td>c_996</td>
      <td>2017-12-10 19:39:53</td>
      <td>2017-12-20</td>
      <td>11:30:00</td>
      <td>2017-12-23</td>
    </tr>
    <tr>
      <th>4019</th>
      <td>r4020</td>
      <td>h_243</td>
      <td>c_996</td>
      <td>2018-04-22 20:41:29</td>
      <td>2018-05-21</td>
      <td>12:00:00</td>
      <td>2018-05-22</td>
    </tr>
    <tr>
      <th>4020</th>
      <td>r4021</td>
      <td>h_159</td>
      <td>c_997</td>
      <td>2016-01-08 20:30:10</td>
      <td>2016-01-09</td>
      <td>12:00:00</td>
      <td>2016-01-11</td>
    </tr>
    <tr>
      <th>4021</th>
      <td>r4022</td>
      <td>h_172</td>
      <td>c_997</td>
      <td>2016-05-13 09:08:55</td>
      <td>2016-06-06</td>
      <td>09:30:00</td>
      <td>2016-06-08</td>
    </tr>
    <tr>
      <th>4022</th>
      <td>r4023</td>
      <td>h_4</td>
      <td>c_999</td>
      <td>2016-04-21 21:50:14</td>
      <td>2016-04-22</td>
      <td>12:00:00</td>
      <td>2016-04-25</td>
    </tr>
    <tr>
      <th>4023</th>
      <td>r4024</td>
      <td>h_244</td>
      <td>c_999</td>
      <td>2016-10-06 18:01:34</td>
      <td>2016-10-07</td>
      <td>11:30:00</td>
      <td>2016-10-09</td>
    </tr>
    <tr>
      <th>4024</th>
      <td>r4025</td>
      <td>h_160</td>
      <td>c_999</td>
      <td>2017-03-11 11:56:05</td>
      <td>2017-03-27</td>
      <td>10:00:00</td>
      <td>2017-03-30</td>
    </tr>
    <tr>
      <th>4025</th>
      <td>r4026</td>
      <td>h_129</td>
      <td>c_999</td>
      <td>2017-06-27 23:00:02</td>
      <td>2017-07-10</td>
      <td>09:30:00</td>
      <td>2017-07-11</td>
    </tr>
    <tr>
      <th>4026</th>
      <td>r4027</td>
      <td>h_97</td>
      <td>c_999</td>
      <td>2017-09-29 05:24:57</td>
      <td>2017-10-09</td>
      <td>10:30:00</td>
      <td>2017-10-10</td>
    </tr>
    <tr>
      <th>4027</th>
      <td>r4028</td>
      <td>h_27</td>
      <td>c_999</td>
      <td>2018-03-14 05:01:45</td>
      <td>2018-04-02</td>
      <td>11:30:00</td>
      <td>2018-04-04</td>
    </tr>
    <tr>
      <th>4028</th>
      <td>r4029</td>
      <td>h_48</td>
      <td>c_1000</td>
      <td>2016-04-16 15:20:17</td>
      <td>2016-05-10</td>
      <td>09:30:00</td>
      <td>2016-05-13</td>
    </tr>
    <tr>
      <th>4029</th>
      <td>r4030</td>
      <td>h_117</td>
      <td>c_1000</td>
      <td>2016-06-06 08:16:51</td>
      <td>2016-07-06</td>
      <td>09:00:00</td>
      <td>2016-07-09</td>
    </tr>
  </tbody>
</table>
<p>4030 rows × 7 columns</p>
</div>