In [1]:
from preprocess.load_data.data_loader import load_hotel_reserve

In [2]:
customer_tb, hotel_tb, reserve_tb = load_hotel_reserve()

In [3]:
# 下の行から本書スタート
# 予約回数を計算(「3-1 データ数、種類数の算出」の例題を参照)
rsv_cnt_tb = reserve_tb.groupby('hotel_id').size().reset_index()
rsv_cnt_tb.columns = ['hotel_id', 'rsv_cnt']

In [4]:
rsv_cnt_tb

<div>
<style scoped>
    .dataframe tbody tr th:only-of-type {
        vertical-align: middle;
    }

    .dataframe tbody tr th {
        vertical-align: top;
    }

    .dataframe thead th {
        text-align: right;
    }
</style>
<table border="1" class="dataframe">
  <thead>
    <tr style="text-align: right;">
      <th></th>
      <th>hotel_id</th>
      <th>rsv_cnt</th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <th>0</th>
      <td>h_1</td>
      <td>10</td>
    </tr>
    <tr>
      <th>1</th>
      <td>h_10</td>
      <td>3</td>
    </tr>
    <tr>
      <th>2</th>
      <td>h_100</td>
      <td>20</td>
    </tr>
    <tr>
      <th>3</th>
      <td>h_101</td>
      <td>17</td>
    </tr>
    <tr>
      <th>4</th>
      <td>h_102</td>
      <td>13</td>
    </tr>
    <tr>
      <th>5</th>
      <td>h_103</td>
      <td>10</td>
    </tr>
    <tr>
      <th>6</th>
      <td>h_104</td>
      <td>11</td>
    </tr>
    <tr>
      <th>7</th>
      <td>h_105</td>
      <td>15</td>
    </tr>
    <tr>
      <th>8</th>
      <td>h_106</td>
      <td>9</td>
    </tr>
    <tr>
      <th>9</th>
      <td>h_107</td>
      <td>11</td>
    </tr>
    <tr>
      <th>10</th>
      <td>h_108</td>
      <td>12</td>
    </tr>
    <tr>
      <th>11</th>
      <td>h_109</td>
      <td>12</td>
    </tr>
    <tr>
      <th>12</th>
      <td>h_11</td>
      <td>18</td>
    </tr>
    <tr>
      <th>13</th>
      <td>h_110</td>
      <td>13</td>
    </tr>
    <tr>
      <th>14</th>
      <td>h_111</td>
      <td>15</td>
    </tr>
    <tr>
      <th>15</th>
      <td>h_112</td>
      <td>10</td>
    </tr>
    <tr>
      <th>16</th>
      <td>h_113</td>
      <td>13</td>
    </tr>
    <tr>
      <th>17</th>
      <td>h_114</td>
      <td>11</td>
    </tr>
    <tr>
      <th>18</th>
      <td>h_115</td>
      <td>17</td>
    </tr>
    <tr>
      <th>19</th>
      <td>h_116</td>
      <td>16</td>
    </tr>
    <tr>
      <th>20</th>
      <td>h_117</td>
      <td>13</td>
    </tr>
    <tr>
      <th>21</th>
      <td>h_118</td>
      <td>17</td>
    </tr>
    <tr>
      <th>22</th>
      <td>h_119</td>
      <td>17</td>
    </tr>
    <tr>
      <th>23</th>
      <td>h_12</td>
      <td>10</td>
    </tr>
    <tr>
      <th>24</th>
      <td>h_120</td>
      <td>15</td>
    </tr>
    <tr>
      <th>25</th>
      <td>h_121</td>
      <td>13</td>
    </tr>
    <tr>
      <th>26</th>
      <td>h_122</td>
      <td>13</td>
    </tr>
    <tr>
      <th>27</th>
      <td>h_123</td>
      <td>11</td>
    </tr>
    <tr>
      <th>28</th>
      <td>h_124</td>
      <td>10</td>
    </tr>
    <tr>
      <th>29</th>
      <td>h_125</td>
      <td>13</td>
    </tr>
    <tr>
      <th>...</th>
      <td>...</td>
      <td>...</td>
    </tr>
    <tr>
      <th>270</th>
      <td>h_72</td>
      <td>19</td>
    </tr>
    <tr>
      <th>271</th>
      <td>h_73</td>
      <td>14</td>
    </tr>
    <tr>
      <th>272</th>
      <td>h_74</td>
      <td>11</td>
    </tr>
    <tr>
      <th>273</th>
      <td>h_75</td>
      <td>12</td>
    </tr>
    <tr>
      <th>274</th>
      <td>h_76</td>
      <td>6</td>
    </tr>
    <tr>
      <th>275</th>
      <td>h_77</td>
      <td>16</td>
    </tr>
    <tr>
      <th>276</th>
      <td>h_78</td>
      <td>19</td>
    </tr>
    <tr>
      <th>277</th>
      <td>h_79</td>
      <td>11</td>
    </tr>
    <tr>
      <th>278</th>
      <td>h_8</td>
      <td>10</td>
    </tr>
    <tr>
      <th>279</th>
      <td>h_80</td>
      <td>15</td>
    </tr>
    <tr>
      <th>280</th>
      <td>h_81</td>
      <td>12</td>
    </tr>
    <tr>
      <th>281</th>
      <td>h_82</td>
      <td>23</td>
    </tr>
    <tr>
      <th>282</th>
      <td>h_83</td>
      <td>9</td>
    </tr>
    <tr>
      <th>283</th>
      <td>h_84</td>
      <td>10</td>
    </tr>
    <tr>
      <th>284</th>
      <td>h_85</td>
      <td>14</td>
    </tr>
    <tr>
      <th>285</th>
      <td>h_86</td>
      <td>10</td>
    </tr>
    <tr>
      <th>286</th>
      <td>h_87</td>
      <td>12</td>
    </tr>
    <tr>
      <th>287</th>
      <td>h_88</td>
      <td>13</td>
    </tr>
    <tr>
      <th>288</th>
      <td>h_89</td>
      <td>13</td>
    </tr>
    <tr>
      <th>289</th>
      <td>h_9</td>
      <td>11</td>
    </tr>
    <tr>
      <th>290</th>
      <td>h_90</td>
      <td>17</td>
    </tr>
    <tr>
      <th>291</th>
      <td>h_91</td>
      <td>11</td>
    </tr>
    <tr>
      <th>292</th>
      <td>h_92</td>
      <td>17</td>
    </tr>
    <tr>
      <th>293</th>
      <td>h_93</td>
      <td>10</td>
    </tr>
    <tr>
      <th>294</th>
      <td>h_94</td>
      <td>15</td>
    </tr>
    <tr>
      <th>295</th>
      <td>h_95</td>
      <td>13</td>
    </tr>
    <tr>
      <th>296</th>
      <td>h_96</td>
      <td>13</td>
    </tr>
    <tr>
      <th>297</th>
      <td>h_97</td>
      <td>16</td>
    </tr>
    <tr>
      <th>298</th>
      <td>h_98</td>
      <td>17</td>
    </tr>
    <tr>
      <th>299</th>
      <td>h_99</td>
      <td>14</td>
    </tr>
  </tbody>
</table>
<p>300 rows × 2 columns</p>
</div>

In [5]:
# 予約回数をもとに順位を計算
# ascendingをFalseにすることで降順に指定
# methodをminに指定し、同じ値の場合は取り得る最小順位に指定
rsv_cnt_tb['rsv_cnt_rank'] = rsv_cnt_tb['rsv_cnt'] \
  .rank(ascending=False, method='min')

In [6]:
rsv_cnt_tb

<div>
<style scoped>
    .dataframe tbody tr th:only-of-type {
        vertical-align: middle;
    }

    .dataframe tbody tr th {
        vertical-align: top;
    }

    .dataframe thead th {
        text-align: right;
    }
</style>
<table border="1" class="dataframe">
  <thead>
    <tr style="text-align: right;">
      <th></th>
      <th>hotel_id</th>
      <th>rsv_cnt</th>
      <th>rsv_cnt_rank</th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <th>0</th>
      <td>h_1</td>
      <td>10</td>
      <td>235.0</td>
    </tr>
    <tr>
      <th>1</th>
      <td>h_10</td>
      <td>3</td>
      <td>300.0</td>
    </tr>
    <tr>
      <th>2</th>
      <td>h_100</td>
      <td>20</td>
      <td>12.0</td>
    </tr>
    <tr>
      <th>3</th>
      <td>h_101</td>
      <td>17</td>
      <td>43.0</td>
    </tr>
    <tr>
      <th>4</th>
      <td>h_102</td>
      <td>13</td>
      <td>139.0</td>
    </tr>
    <tr>
      <th>5</th>
      <td>h_103</td>
      <td>10</td>
      <td>235.0</td>
    </tr>
    <tr>
      <th>6</th>
      <td>h_104</td>
      <td>11</td>
      <td>202.0</td>
    </tr>
    <tr>
      <th>7</th>
      <td>h_105</td>
      <td>15</td>
      <td>88.0</td>
    </tr>
    <tr>
      <th>8</th>
      <td>h_106</td>
      <td>9</td>
      <td>260.0</td>
    </tr>
    <tr>
      <th>9</th>
      <td>h_107</td>
      <td>11</td>
      <td>202.0</td>
    </tr>
    <tr>
      <th>10</th>
      <td>h_108</td>
      <td>12</td>
      <td>175.0</td>
    </tr>
    <tr>
      <th>11</th>
      <td>h_109</td>
      <td>12</td>
      <td>175.0</td>
    </tr>
    <tr>
      <th>12</th>
      <td>h_11</td>
      <td>18</td>
      <td>32.0</td>
    </tr>
    <tr>
      <th>13</th>
      <td>h_110</td>
      <td>13</td>
      <td>139.0</td>
    </tr>
    <tr>
      <th>14</th>
      <td>h_111</td>
      <td>15</td>
      <td>88.0</td>
    </tr>
    <tr>
      <th>15</th>
      <td>h_112</td>
      <td>10</td>
      <td>235.0</td>
    </tr>
    <tr>
      <th>16</th>
      <td>h_113</td>
      <td>13</td>
      <td>139.0</td>
    </tr>
    <tr>
      <th>17</th>
      <td>h_114</td>
      <td>11</td>
      <td>202.0</td>
    </tr>
    <tr>
      <th>18</th>
      <td>h_115</td>
      <td>17</td>
      <td>43.0</td>
    </tr>
    <tr>
      <th>19</th>
      <td>h_116</td>
      <td>16</td>
      <td>60.0</td>
    </tr>
    <tr>
      <th>20</th>
      <td>h_117</td>
      <td>13</td>
      <td>139.0</td>
    </tr>
    <tr>
      <th>21</th>
      <td>h_118</td>
      <td>17</td>
      <td>43.0</td>
    </tr>
    <tr>
      <th>22</th>
      <td>h_119</td>
      <td>17</td>
      <td>43.0</td>
    </tr>
    <tr>
      <th>23</th>
      <td>h_12</td>
      <td>10</td>
      <td>235.0</td>
    </tr>
    <tr>
      <th>24</th>
      <td>h_120</td>
      <td>15</td>
      <td>88.0</td>
    </tr>
    <tr>
      <th>25</th>
      <td>h_121</td>
      <td>13</td>
      <td>139.0</td>
    </tr>
    <tr>
      <th>26</th>
      <td>h_122</td>
      <td>13</td>
      <td>139.0</td>
    </tr>
    <tr>
      <th>27</th>
      <td>h_123</td>
      <td>11</td>
      <td>202.0</td>
    </tr>
    <tr>
      <th>28</th>
      <td>h_124</td>
      <td>10</td>
      <td>235.0</td>
    </tr>
    <tr>
      <th>29</th>
      <td>h_125</td>
      <td>13</td>
      <td>139.0</td>
    </tr>
    <tr>
      <th>...</th>
      <td>...</td>
      <td>...</td>
      <td>...</td>
    </tr>
    <tr>
      <th>270</th>
      <td>h_72</td>
      <td>19</td>
      <td>20.0</td>
    </tr>
    <tr>
      <th>271</th>
      <td>h_73</td>
      <td>14</td>
      <td>115.0</td>
    </tr>
    <tr>
      <th>272</th>
      <td>h_74</td>
      <td>11</td>
      <td>202.0</td>
    </tr>
    <tr>
      <th>273</th>
      <td>h_75</td>
      <td>12</td>
      <td>175.0</td>
    </tr>
    <tr>
      <th>274</th>
      <td>h_76</td>
      <td>6</td>
      <td>293.0</td>
    </tr>
    <tr>
      <th>275</th>
      <td>h_77</td>
      <td>16</td>
      <td>60.0</td>
    </tr>
    <tr>
      <th>276</th>
      <td>h_78</td>
      <td>19</td>
      <td>20.0</td>
    </tr>
    <tr>
      <th>277</th>
      <td>h_79</td>
      <td>11</td>
      <td>202.0</td>
    </tr>
    <tr>
      <th>278</th>
      <td>h_8</td>
      <td>10</td>
      <td>235.0</td>
    </tr>
    <tr>
      <th>279</th>
      <td>h_80</td>
      <td>15</td>
      <td>88.0</td>
    </tr>
    <tr>
      <th>280</th>
      <td>h_81</td>
      <td>12</td>
      <td>175.0</td>
    </tr>
    <tr>
      <th>281</th>
      <td>h_82</td>
      <td>23</td>
      <td>5.0</td>
    </tr>
    <tr>
      <th>282</th>
      <td>h_83</td>
      <td>9</td>
      <td>260.0</td>
    </tr>
    <tr>
      <th>283</th>
      <td>h_84</td>
      <td>10</td>
      <td>235.0</td>
    </tr>
    <tr>
      <th>284</th>
      <td>h_85</td>
      <td>14</td>
      <td>115.0</td>
    </tr>
    <tr>
      <th>285</th>
      <td>h_86</td>
      <td>10</td>
      <td>235.0</td>
    </tr>
    <tr>
      <th>286</th>
      <td>h_87</td>
      <td>12</td>
      <td>175.0</td>
    </tr>
    <tr>
      <th>287</th>
      <td>h_88</td>
      <td>13</td>
      <td>139.0</td>
    </tr>
    <tr>
      <th>288</th>
      <td>h_89</td>
      <td>13</td>
      <td>139.0</td>
    </tr>
    <tr>
      <th>289</th>
      <td>h_9</td>
      <td>11</td>
      <td>202.0</td>
    </tr>
    <tr>
      <th>290</th>
      <td>h_90</td>
      <td>17</td>
      <td>43.0</td>
    </tr>
    <tr>
      <th>291</th>
      <td>h_91</td>
      <td>11</td>
      <td>202.0</td>
    </tr>
    <tr>
      <th>292</th>
      <td>h_92</td>
      <td>17</td>
      <td>43.0</td>
    </tr>
    <tr>
      <th>293</th>
      <td>h_93</td>
      <td>10</td>
      <td>235.0</td>
    </tr>
    <tr>
      <th>294</th>
      <td>h_94</td>
      <td>15</td>
      <td>88.0</td>
    </tr>
    <tr>
      <th>295</th>
      <td>h_95</td>
      <td>13</td>
      <td>139.0</td>
    </tr>
    <tr>
      <th>296</th>
      <td>h_96</td>
      <td>13</td>
      <td>139.0</td>
    </tr>
    <tr>
      <th>297</th>
      <td>h_97</td>
      <td>16</td>
      <td>60.0</td>
    </tr>
    <tr>
      <th>298</th>
      <td>h_98</td>
      <td>17</td>
      <td>43.0</td>
    </tr>
    <tr>
      <th>299</th>
      <td>h_99</td>
      <td>14</td>
      <td>115.0</td>
    </tr>
  </tbody>
</table>
<p>300 rows × 3 columns</p>
</div>

In [7]:
# 必要のないrsv_cntの列を削除
rsv_cnt_tb.drop('rsv_cnt', axis=1, inplace=True)

In [8]:
rsv_cnt_tb

<div>
<style scoped>
    .dataframe tbody tr th:only-of-type {
        vertical-align: middle;
    }

    .dataframe tbody tr th {
        vertical-align: top;
    }

    .dataframe thead th {
        text-align: right;
    }
</style>
<table border="1" class="dataframe">
  <thead>
    <tr style="text-align: right;">
      <th></th>
      <th>hotel_id</th>
      <th>rsv_cnt_rank</th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <th>0</th>
      <td>h_1</td>
      <td>235.0</td>
    </tr>
    <tr>
      <th>1</th>
      <td>h_10</td>
      <td>300.0</td>
    </tr>
    <tr>
      <th>2</th>
      <td>h_100</td>
      <td>12.0</td>
    </tr>
    <tr>
      <th>3</th>
      <td>h_101</td>
      <td>43.0</td>
    </tr>
    <tr>
      <th>4</th>
      <td>h_102</td>
      <td>139.0</td>
    </tr>
    <tr>
      <th>5</th>
      <td>h_103</td>
      <td>235.0</td>
    </tr>
    <tr>
      <th>6</th>
      <td>h_104</td>
      <td>202.0</td>
    </tr>
    <tr>
      <th>7</th>
      <td>h_105</td>
      <td>88.0</td>
    </tr>
    <tr>
      <th>8</th>
      <td>h_106</td>
      <td>260.0</td>
    </tr>
    <tr>
      <th>9</th>
      <td>h_107</td>
      <td>202.0</td>
    </tr>
    <tr>
      <th>10</th>
      <td>h_108</td>
      <td>175.0</td>
    </tr>
    <tr>
      <th>11</th>
      <td>h_109</td>
      <td>175.0</td>
    </tr>
    <tr>
      <th>12</th>
      <td>h_11</td>
      <td>32.0</td>
    </tr>
    <tr>
      <th>13</th>
      <td>h_110</td>
      <td>139.0</td>
    </tr>
    <tr>
      <th>14</th>
      <td>h_111</td>
      <td>88.0</td>
    </tr>
    <tr>
      <th>15</th>
      <td>h_112</td>
      <td>235.0</td>
    </tr>
    <tr>
      <th>16</th>
      <td>h_113</td>
      <td>139.0</td>
    </tr>
    <tr>
      <th>17</th>
      <td>h_114</td>
      <td>202.0</td>
    </tr>
    <tr>
      <th>18</th>
      <td>h_115</td>
      <td>43.0</td>
    </tr>
    <tr>
      <th>19</th>
      <td>h_116</td>
      <td>60.0</td>
    </tr>
    <tr>
      <th>20</th>
      <td>h_117</td>
      <td>139.0</td>
    </tr>
    <tr>
      <th>21</th>
      <td>h_118</td>
      <td>43.0</td>
    </tr>
    <tr>
      <th>22</th>
      <td>h_119</td>
      <td>43.0</td>
    </tr>
    <tr>
      <th>23</th>
      <td>h_12</td>
      <td>235.0</td>
    </tr>
    <tr>
      <th>24</th>
      <td>h_120</td>
      <td>88.0</td>
    </tr>
    <tr>
      <th>25</th>
      <td>h_121</td>
      <td>139.0</td>
    </tr>
    <tr>
      <th>26</th>
      <td>h_122</td>
      <td>139.0</td>
    </tr>
    <tr>
      <th>27</th>
      <td>h_123</td>
      <td>202.0</td>
    </tr>
    <tr>
      <th>28</th>
      <td>h_124</td>
      <td>235.0</td>
    </tr>
    <tr>
      <th>29</th>
      <td>h_125</td>
      <td>139.0</td>
    </tr>
    <tr>
      <th>...</th>
      <td>...</td>
      <td>...</td>
    </tr>
    <tr>
      <th>270</th>
      <td>h_72</td>
      <td>20.0</td>
    </tr>
    <tr>
      <th>271</th>
      <td>h_73</td>
      <td>115.0</td>
    </tr>
    <tr>
      <th>272</th>
      <td>h_74</td>
      <td>202.0</td>
    </tr>
    <tr>
      <th>273</th>
      <td>h_75</td>
      <td>175.0</td>
    </tr>
    <tr>
      <th>274</th>
      <td>h_76</td>
      <td>293.0</td>
    </tr>
    <tr>
      <th>275</th>
      <td>h_77</td>
      <td>60.0</td>
    </tr>
    <tr>
      <th>276</th>
      <td>h_78</td>
      <td>20.0</td>
    </tr>
    <tr>
      <th>277</th>
      <td>h_79</td>
      <td>202.0</td>
    </tr>
    <tr>
      <th>278</th>
      <td>h_8</td>
      <td>235.0</td>
    </tr>
    <tr>
      <th>279</th>
      <td>h_80</td>
      <td>88.0</td>
    </tr>
    <tr>
      <th>280</th>
      <td>h_81</td>
      <td>175.0</td>
    </tr>
    <tr>
      <th>281</th>
      <td>h_82</td>
      <td>5.0</td>
    </tr>
    <tr>
      <th>282</th>
      <td>h_83</td>
      <td>260.0</td>
    </tr>
    <tr>
      <th>283</th>
      <td>h_84</td>
      <td>235.0</td>
    </tr>
    <tr>
      <th>284</th>
      <td>h_85</td>
      <td>115.0</td>
    </tr>
    <tr>
      <th>285</th>
      <td>h_86</td>
      <td>235.0</td>
    </tr>
    <tr>
      <th>286</th>
      <td>h_87</td>
      <td>175.0</td>
    </tr>
    <tr>
      <th>287</th>
      <td>h_88</td>
      <td>139.0</td>
    </tr>
    <tr>
      <th>288</th>
      <td>h_89</td>
      <td>139.0</td>
    </tr>
    <tr>
      <th>289</th>
      <td>h_9</td>
      <td>202.0</td>
    </tr>
    <tr>
      <th>290</th>
      <td>h_90</td>
      <td>43.0</td>
    </tr>
    <tr>
      <th>291</th>
      <td>h_91</td>
      <td>202.0</td>
    </tr>
    <tr>
      <th>292</th>
      <td>h_92</td>
      <td>43.0</td>
    </tr>
    <tr>
      <th>293</th>
      <td>h_93</td>
      <td>235.0</td>
    </tr>
    <tr>
      <th>294</th>
      <td>h_94</td>
      <td>88.0</td>
    </tr>
    <tr>
      <th>295</th>
      <td>h_95</td>
      <td>139.0</td>
    </tr>
    <tr>
      <th>296</th>
      <td>h_96</td>
      <td>139.0</td>
    </tr>
    <tr>
      <th>297</th>
      <td>h_97</td>
      <td>60.0</td>
    </tr>
    <tr>
      <th>298</th>
      <td>h_98</td>
      <td>43.0</td>
    </tr>
    <tr>
      <th>299</th>
      <td>h_99</td>
      <td>115.0</td>
    </tr>
  </tbody>
</table>
<p>300 rows × 2 columns</p>
</div>